import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/softuidashboardprothumbnail">
            SoftUIDashboardPROThumbnail
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreendefault">DashboardScreenDefault</Link>
        </li>
        <li>
          <Link to="/dashboardscreencrm">DashboardScreenCRM</Link>
        </li>
        <li>
          <Link to="/dashboardscreenprofileoverview">
            DashboardScreenProfileOverview
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenteams">DashboardScreenTeams</Link>
        </li>
        <li>
          <Link to="/dashboardscreenallprojects">
            DashboardScreenAllProjects
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenreports">DashboardScreenReports</Link>
        </li>
        <li>
          <Link to="/dashboardscreennewuser">DashboardScreenNewUser</Link>
        </li>
        <li>
          <Link to="/dashboardscreenaccountbilling">
            DashboardScreenAccountBilling
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenaccountinvoice">
            DashboardScreenAccountInvoice
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenprojectsgeneral">
            DashboardScreenProjectsGeneral
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenprojectstimeline">
            DashboardScreenProjectsTimeline
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenpricing">DashboardScreenPricing</Link>
        </li>
        <li>
          <Link to="/dashboardscreenwidgets">DashboardScreenWidgets</Link>
        </li>
        <li>
          <Link to="/dashboardscreencharts">DashboardScreenCharts</Link>
        </li>
        <li>
          <Link to="/dashboardscreenalerts">DashboardScreenAlerts</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
